version: '3'
services:
    portifolio:
        build:
            dockerfile: Dockerfile
        ports:
            - 4000:4000
        environment:
            PORT: 4000
        volumes:
            - ".:/portifolio"
