name: Deploy Portifolio
on: 
  push:
    branches:
      - 'main'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate new page
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'willgoncruz@users.noreply.github.com'
          git checkout gh-pages
          rm index.html
          make static
          git add .
          git commit -m "Generated static index.html"
          git push
