name: Deploy Portifolio
on: 
  push:
    branches:
      - 'main'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'gh-pages'
      - name: Generate new page
        run: |
          make static
          # git config --global user.name 'William Cruz'
          # git config --global user.email 'willgoncruz@users.noreply.github.com'
          # git commit -am "Generated static index.html"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Generated static index.html"
          git push
